version: '3.3'

services:
    api:
        image: sa2020prototype/rabbitapi
        ports:
            - "80:80"
        networks:
            ingress:

    rabbitmqserver:
        image: rabbitmq:3-management
        ports: # same as the docker image exposes
            - "4369:4369"
            - "5672:5672"
            - "15672:15672"
            - "25672:25672"
        tty: true
        networks:
            ingress:

    file_service:
        image: sa2020prototype/rabbitmqfileservice
        depends_on:
            - "rabbitmqserver"
        restart:
            always
        tty: true
        networks:
            ingress:
    
    plag_service:
        image: sa2020prototype/rabbitmqplagservice
        depends_on:
            - "rabbitmqserver"
        restart:
            always
        tty: true
        networks:
            ingress:


networks:
    ingress:
