version: '3.3'

services:
    api:
        image: sa2020prototype/rabbitapi
        ports:
            - "80:80"
        networks:
            sa2020http:
                ipv4_address: 172.100.18.10

    rabbitmqserver:
        image: rabbitmq:3-management
        ports: 
            - "5672:5672"
            - "15672:15672"
        tty: true
        networks:
            sa2020http:
                ipv4_address: 172.100.18.2

    file_service:
        image: sa2020prototype/rabbitmqfileservice
        depends_on:
            - "rabbitmqserver"
        restart:
            always
        tty: true
        networks:
            sa2020http:
                ipv4_address: 172.100.18.3
    
    plag_service:
        image: sa2020prototype/rabbitmqplagservice
        depends_on:
            - "rabbitmqserver"
        restart:
            always
        tty: true
        networks:
            sa2020http:
                ipv4_address: 172.100.18.4
    
    # simulator:
    #     image: sa2020prototype/rabbitmqsimulator
    #     # ports:
    #     #     - "5673:5672"
    #     depends_on:
    #         - "rabbitmqserver"
    #         - "file_service"
    #     restart:
    #         always
    #     tty: true
    #     networks:
    #         sa2020http:
    #             ipv4_address: 172.100.18.4

networks:
    sa2020http:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
            - subnet: 172.100.18.0/24